/**
 * 用来定义action type类型常量模块
 */

export const SAVE_USER = 'SAVE_USER';
export const REMOVE_USET = 'REMOVE_USET';
export const CHANGE_ANGUAGE = 'CHANGE_ANGUAGE';
export const GET_CATEGOR_YLIST = 'GET_CATEGOR_YLIST';
export const ADD_CATEGOR_CATEGOTY = 'ADD_CATEGOR_CATEGOTY';
export const DELETE_CATEGOR_CATEGOTY = 'DELETE_CATEGOR_CATEGOTY';
export const UPDAYE_CATEGOR_CATEGOTY = 'UPDAYE_CATEGOR_CATEGOTY';
export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_SEARCH_PRODUCT = 'SET_SEARCH_PRODUCT'